import type { Metadata } from "next";
import "./globals.css";

import styles from './layout.module.scss'
import Menu from "@/components/menu";
import { redirect } from "next/navigation";

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,team,analytics,modal
}: Readonly<{
  children: React.ReactNode,
  team: React.ReactNode,
  analytics: React.ReactNode,
  modal: React.ReactNode
}>) {
  return (
    <html lang="en">
      <body>
        <div className={styles.main}>
        <div className={styles.menu}>
          <Menu />
          <span>haha</span>
        </div>
        <div className={styles.content}>
          <div>{children}</div>
          <div>{team}</div>
          <div>{analytics}</div>
          <div>{modal}</div>
        </div>
        </div>
        
        
      </body>
    </html>
  );
}
